package votingApplication;


/**
* votingApplication/_VoterImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votingApplication.idl
* lundi 9 avril 2007 23 h 37 CEST
*/

public abstract class _VoterImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements votingApplication.Voter, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _VoterImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_INSEE", new java.lang.Integer (0));
    _methods.put ("_set_INSEE", new java.lang.Integer (1));
    _methods.put ("_get_password", new java.lang.Integer (2));
    _methods.put ("_set_password", new java.lang.Integer (3));
    _methods.put ("_get_firstName", new java.lang.Integer (4));
    _methods.put ("_set_firstName", new java.lang.Integer (5));
    _methods.put ("_get_lastName", new java.lang.Integer (6));
    _methods.put ("_set_lastName", new java.lang.Integer (7));
    _methods.put ("_get_department", new java.lang.Integer (8));
    _methods.put ("_set_department", new java.lang.Integer (9));
    _methods.put ("registerVote", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // votingApplication/Voter/_get_INSEE
       {
         String $result = null;
         $result = this.INSEE ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // votingApplication/Voter/_set_INSEE
       {
         String newINSEE = in.read_string ();
         this.INSEE (newINSEE);
         out = $rh.createReply();
         break;
       }

       case 2:  // votingApplication/Voter/_get_password
       {
         String $result = null;
         $result = this.password ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // votingApplication/Voter/_set_password
       {
         String newPassword = in.read_string ();
         this.password (newPassword);
         out = $rh.createReply();
         break;
       }

       case 4:  // votingApplication/Voter/_get_firstName
       {
         String $result = null;
         $result = this.firstName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // votingApplication/Voter/_set_firstName
       {
         String newFirstName = in.read_string ();
         this.firstName (newFirstName);
         out = $rh.createReply();
         break;
       }

       case 6:  // votingApplication/Voter/_get_lastName
       {
         String $result = null;
         $result = this.lastName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // votingApplication/Voter/_set_lastName
       {
         String newLastName = in.read_string ();
         this.lastName (newLastName);
         out = $rh.createReply();
         break;
       }

       case 8:  // votingApplication/Voter/_get_department
       {
         short $result = (short)0;
         $result = this.department ();
         out = $rh.createReply();
         out.write_short ($result);
         break;
       }

       case 9:  // votingApplication/Voter/_set_department
       {
         short newDepartment = in.read_short ();
         this.department (newDepartment);
         out = $rh.createReply();
         break;
       }

       case 10:  // votingApplication/Voter/registerVote
       {
         String aCandidate = in.read_string ();
         String aMachine = in.read_string ();
         this.registerVote (aCandidate, aMachine);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:votingApplication/Voter:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _VoterImplBase
