package votingApplication;


/**
* votingApplication/Candidate.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votingApplication.idl
* lundi 9 avril 2007 23 h 37 CEST
*/

public final class Candidate implements org.omg.CORBA.portable.IDLEntity
{
  public String candidateNumber = null;
  public String firstName = null;
  public String lastName = null;
  public short age = (short)0;
  public String profession = null;
  public String mandates = null;
  public String description = null;

  public Candidate ()
  {
  } // ctor

  public Candidate (String _candidateNumber, String _firstName, String _lastName, short _age, String _profession, String _mandates, String _description)
  {
    candidateNumber = _candidateNumber;
    firstName = _firstName;
    lastName = _lastName;
    age = _age;
    profession = _profession;
    mandates = _mandates;
    description = _description;
  } // ctor

} // class Candidate
