package votingApplication;


/**
* votingApplication/ListeCandidatesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votingApplication.idl
* lundi 9 avril 2007 23 h 37 CEST
*/

public final class ListeCandidatesHolder implements org.omg.CORBA.portable.Streamable
{
  public votingApplication.Candidate value[] = null;

  public ListeCandidatesHolder ()
  {
  }

  public ListeCandidatesHolder (votingApplication.Candidate[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = votingApplication.ListeCandidatesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    votingApplication.ListeCandidatesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return votingApplication.ListeCandidatesHelper.type ();
  }

}
