package votingApplication;


/**
* votingApplication/ResultData.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from VotingApplication.idl
* mardi 17 avril 2007 18 h 27 CEST
*/

public final class ResultData implements org.omg.CORBA.portable.IDLEntity
{
  public String firstName = null;
  public String lastName = null;
  public String department = null;
  public String canton = null;
  public String district = null;
  public String office = null;

  public ResultData ()
  {
  } // ctor

  public ResultData (String _firstName, String _lastName, String _department, String _canton, String _district, String _office)
  {
    firstName = _firstName;
    lastName = _lastName;
    department = _department;
    canton = _canton;
    district = _district;
    office = _office;
  } // ctor

} // class ResultData
