package votingApplication;

/**
* votingApplication/ResultDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from VotingApplication.idl
* mardi 17 avril 2007 18 h 27 CEST
*/

public final class ResultDataHolder implements org.omg.CORBA.portable.Streamable
{
  public votingApplication.ResultData value = null;

  public ResultDataHolder ()
  {
  }

  public ResultDataHolder (votingApplication.ResultData initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = votingApplication.ResultDataHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    votingApplication.ResultDataHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return votingApplication.ResultDataHelper.type ();
  }

}
