package votingApplication;


/**
* votingApplication/VoterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votingApplication.idl
* lundi 9 avril 2007 23 h 37 CEST
*/

public interface VoterOperations 
{
  String INSEE ();
  void INSEE (String newINSEE);
  String password ();
  void password (String newPassword);
  String firstName ();
  void firstName (String newFirstName);
  String lastName ();
  void lastName (String newLastName);
  short department ();
  void department (short newDepartment);
  void registerVote (String aCandidate, String aMachine);
} // interface VoterOperations
