package votingApplication;

/**
* votingApplication/VoterHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votingApplication.idl
* lundi 9 avril 2007 23 h 37 CEST
*/

public final class VoterHolder implements org.omg.CORBA.portable.Streamable
{
  public votingApplication.Voter value = null;

  public VoterHolder ()
  {
  }

  public VoterHolder (votingApplication.Voter initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = votingApplication.VoterHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    votingApplication.VoterHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return votingApplication.VoterHelper.type ();
  }

}
