package votingApplication;


/**
* votingApplication/VotingMachineOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from votingApplication.idl
* lundi 9 avril 2007 23 h 37 CEST
*/

public interface VotingMachineOperations 
{
  String serial ();
  void serial (String newSerial);
  String canton ();
  void canton (String newCanton);
  String district ();
  void district (String newDistrict);
  short department ();
  void department (short newDepartment);
  String office ();
  void office (String newOffice);
  boolean checkAccess (votingApplication.Voter aVoter);
  String checkRightToVote (String insee);
  votingApplication.Candidate[] getCandidates ();
  void initMAV ();
} // interface VotingMachineOperations
