package votingApplication;


/**
* votingApplication/VTR.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from VotingApplication.idl
* mardi 17 avril 2007 18 h 27 CEST
*/

public interface VTR extends VTROperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface VTR
