package votingApplication;

/**
* votingApplication/VTRHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from VotingApplication.idl
* mardi 17 avril 2007 18 h 27 CEST
*/

public final class VTRHolder implements org.omg.CORBA.portable.Streamable
{
  public votingApplication.VTR value = null;

  public VTRHolder ()
  {
  }

  public VTRHolder (votingApplication.VTR initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = votingApplication.VTRHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    votingApplication.VTRHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return votingApplication.VTRHelper.type ();
  }

}
