package votingApplication;


/**
* votingApplication/VTRHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from VotingApplication.idl
* mardi 17 avril 2007 18 h 27 CEST
*/

abstract public class VTRHelper
{
  private static String  _id = "IDL:votingApplication/VTR:1.0";

  public static void insert (org.omg.CORBA.Any a, votingApplication.VTR that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static votingApplication.VTR extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (votingApplication.VTRHelper.id (), "VTR");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static votingApplication.VTR read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_VTRStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, votingApplication.VTR value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static votingApplication.VTR narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof votingApplication.VTR)
      return (votingApplication.VTR)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      votingApplication._VTRStub stub = new votingApplication._VTRStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
