package votingApplication;


/**
* votingApplication/VTROperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from VotingApplication.idl
* mardi 17 avril 2007 18 h 27 CEST
*/

public interface VTROperations 
{
  votingApplication.ResultData[] getResults ();
} // interface VTROperations
